### ISSUE TITLE
Newline after prompt 

### ISSUE THREAD

**Issue by itsdeadguy** [eendroroy/alien-minimal#10]
* **I'm submitting a ...**
feature request

* **Do you want to request a *feature* or report a *bug*?**
*feature*

* **What is the current behavior?**
prompt and command output don't have a blank line in between them

* **What is the expected behavior?**
have it show a blank line, like it does in the non-minimal alien

* **What is the motivation / use case for changing the behavior?**
I feel it would look cleaner

* **Please tell us about your environment:**

- Plugin Manager: zplugin
- ZSH Version 5.5.1

**Comment by eendroroy** [comment]
Always show a new line

```bash
AM_INITIAL_LINE_FEED=1
```

Only show new for non-empty input (pressing enter with out writing anything will not print a new line)

```bash
AM_INITIAL_LINE_FEED=2
```

Unset `AM_INITIAL_LINE_FEED` to never print a new line.
