### ISSUE TITLE
Vim mode indicator

### ISSUE THREAD

**Issue by itsdeadguy** [eendroroy/alien-minimal#11]
* **I'm submitting a ...**
feature request

* **What is the current behavior?**
There is no way to tell if one is in insert or command mode

* **What is the expected behavior?**
there should be a visible way to tell if i'm inserting commands into the prompt, or editing them in command mode

* **What is the motivation / use case for changing the behavior?**
Having vim mode on the shell is great, especially if you need to edit long commands and things like that, it can make motion fast too.

* **Please tell us about your environment:**

- Plugin Manager: zplugin 
- ZSH Version 5.5.1

* **Other information** 
Back when i was using Pure prompt, i had found a solution to this in their wiki where it would allow you to use the prompt character as indicator instead of having to add yet another character to the prompt.
The code looked like this
```
VIM_PROMPT=">"
PROMPT='%(?.%B%F{green}.%B%F{red}>%B%F{green})${VIM_PROMPT}%b%f '
prompt_pure_update_vim_prompt() {
	zle || {
	    print "error: pure_update_vim_prompt must be called when zle is active"
	    return 1
	}
	VIM_PROMPT=${${KEYMAP/vicmd/<}/(main|viins)/>}
	zle .reset-prompt
}

function zle-line-init zle-keymap-select {
	prompt_pure_update_vim_prompt
}
export KEYTIMEOUT=1
zle -N zle-line-init
zle -N zle-keymap-select
```
This way your prompt would look like
```
> ~ really-long-command-here
```
in insert mode, and like this
```
< ~ really-long-command-here
```
in command mode.
I feel doing it this way would be in keeping with the minimalness of the theme while adding a nice feature.
But of course, i'm not married to this approach or anything like that.

**Comment by eendroroy** [comment]
Hi @CadaverLab ,

I am trying to implemented what you proposed.
Need a help if you can. Do you know a way to check if vi-mode is enabled or not?
