### ISSUE TITLE
Error when git repo has no commits yet

### ISSUE THREAD

**Issue by sandangel** [eendroroy/alien-minimal#14]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 
go to a git repo with no commit

```sh
fatal: your current branch 'master' does not have any commits yet
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

* **What is the expected behavior?**
There should be no error.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Plugin Manager: [antigen | zplug | oh-my-zsh | ... ] antigen
- ZSH Version 5

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, etc)

**Comment by jkhsjdhjs** [comment]
I still experience this issue. The following errors are printed:
```
fatal: your current branch 'master' does not have any commits yet
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
am_git_stash:1: command not found: plib_git_stash
```

BTW: I'm not using `oh-my-zsh` anymore, just zsh with `grml-zsh-config`, `zsh-syntax-highlighting`, `zsh-autosuggestions` and this theme.

The following is printed also when the repo has commits: `am_git_stash:1: command not found: plib_git_stash`

**Comment by eendroroy** [comment]
Do you use any plugin manager, like antigen/zplug etc.?

**Comment by jkhsjdhjs** [comment]
Nope, just using `prompt alien-minimal` in my `.zshrc.local`.

My config files:
**.zshrc.local**
```
# alien-minimal configuration
export PROMPT_START_TAG='>> '
export PROMPT_END_TAG=' %%'
export PROMPT_START_TAG_COLOR=10
export PROMPT_END_TAG_COLOR=81
export AM_SHOW_FULL_DIR=1
export AM_ERROR_ON_START_TAG=1
export AM_HIDE_EXIT_CODE=1
export am_error_color=9

source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

prompt alien-minimal
```

**.zshenv**
```
typeset -U fpath
fpath=(~/.zprompts $fpath[@])

export PATH="$HOME/esp/xtensa-esp32-elf/bin:/usr/local/texlive/2018/bin/x86_64-linux/:$PATH"
export EDITOR="nvim"
export GPG_TTY="$(tty)"
export IDF_PATH="$HOME/esp/esp-idf"
```

The theme is located in `~/.zprompts/alien-minimal`.

**Comment by eendroroy** [comment]
Sorry for the delay to reply.

Could you please check on which commit your local copy is?

**Comment by jkhsjdhjs** [comment]
Yes, it's on `719f4df`, the latest commit to master.

EDIT: I did a `git status` and noticed there were new commits for two submodules available. I updated them and the issue is gone. Thanks for your support!

**Comment by eendroroy** [comment]
Glad to know the issue is gone. :)
