### ISSUE TITLE
UX Improve: show previous prompt while waiting for async task

### ISSUE THREAD

**Issue by sandangel** [eendroroy/alien-minimal#15]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**
whenever I hit Enter, the right prompt disappear while waiting for the async update

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 

* **What is the expected behavior?**
it should show the previous status while waiting for git status update. when the new status available, it could replace the old one.

* **What is the motivation / use case for changing the behavior?**
Better UX

* **Please tell us about your environment:**

- Plugin Manager: [antigen | zplug | oh-my-zsh | ... ]
- ZSH Version

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, etc)

**Comment by eendroroy** [comment]
### Keep previous RPROMPT

```bash
export AM_KEEP_PROMPT=1
```

This will keep previous right prompt while new right prompt is being rendered.
