### ISSUE TITLE
Customization limiting "Design flaw"

### ISSUE THREAD

**Issue by louis-vinchon** [eendroroy/alien-minimal#18]
**I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request
  - [x] Question / Suggestion / Remark

Maybe I should post it on your library [promptlib-zsh](https://github.com/eendroroy/promptlib-zsh) instead, more detail on that further down the page.

## Context

I am currently implementing some simple features on my fork of the project and I found what I would qualify as a design flaw where the [single responsibility principle](https://en.wikipedia.org/wiki/Single_responsibility_principle) isn't respected, which makes customization harder:

Most of the prompt parts have customizable colors, symbols, and we can even choose, for some of them, whether or not they should appear. So far so good BUT:

## Problem

You are using your helper library [promptlib-zsh](https://github.com/eendroroy/promptlib-zsh) which handles all the little tasks such as determining versions, git branches, etc...

The issue I encountered in `alien-minimal` is that I don't have much control over the "branch status" part (colors, icons ...) which is generated by [am_git_dirty](https://github.com/eendroroy/alien-minimal/blob/master/modules/git.zsh#L15). Of course we can use the environment variables [as specified in the documentation](https://github.com/eendroroy/alien-minimal/blob/master/modules/git.zsh#L15) but I, developer, expected to be able to tweak every **aspect** of my prompt, including separators, just by editing this project's code. The current environment variables do not offer enough options to my taste.

The root of the issue is that [plib_git_dirty](https://github.com/eendroroy/promptlib-zsh/blob/master/modules/git.zsh#L47) is responsible for getting the status of the git branche ... **but also the formatting**, which is where I think it breaks the single responibilty principle. Most of the other function only return raw data, but not `plib_git_dirty`, it does more than that.

## Consequence

What that means for me is that if I want to modify the way branch status is displayed, e.g.
  - Display the number of modified / added / deleted files
  - Have a blank space instead of the symbol if there was no changes (will make the layout more stable visually speaking)

I simply can't do it without ugly, heavy, complicated parsing of `plib_git_dirty`'s returned value (and even then I couldn't get the number of modified files for instance) when it should have just returned data.
I could also fork promptlib-zsh as well, but I would be forking and tweaking two projects for one result because one of the two does a little of both tasks.

## Suggested fix

I think the project is well structured and the objective was obviously to have it very modular but this particular implementation is not.

What I suggest is to move everything format-related from `plib_git_dirty` to `alien-minimal`. As a "theme plugin" am should handle **ALL** formatting.

If you agree with these "requested changes" as I would call it, I could make the two PRs. Tbh I'm just done with writing this ... and I just realized I should have coded it in the first place ... because I'll do it anyway.

## My environment
- Plugin Manager: antigen
- ZSH Version: 5.7.1

**Comment by eendroroy** [comment]
Yes, the `plib_git_dirty` method was indeed does not follow the other methods. I wrote it in hurry and since not much development has been done for the theme, I never really thought of refactoring it. If you can refactor the method, it would be a great help for me. 

Please go ahead with the PRs. :)

**Comment by louis-vinchon** [comment]
[Promptlib PR](https://github.com/eendroroy/promptlib-zsh/pull/4)
[Alien-minimal PR](https://github.com/eendroroy/alien-minimal/pull/19)

I tried to preserve the original layout as much as I could. I think I got it right but I'm naturally biased on the matter.

**Comment by eendroroy** [comment]
Merged the PRs.
Thanks a lot :)
