### ISSUE TITLE
How to add some characters to prompt

### ISSUE THREAD

**Issue by ijsnow** [eendroroy/alien-minimal#2]
I love the theme :) super simple, just what I wanted. 

I was trying to mess with it a little to add an arrow and a dollar sign(I know, making it less simple which I just said I wanted ¯\_(ツ)_/¯)

Basically I want it to be `→ my-dir $ some-command` instead of `my-dir some-command`

The problem is when I add characters to the prompt the alignment gets all messed up. Any tips on how to do this from a fork of your repo? 

Thanks!

**Comment by eendroroy** [comment]
I am really happy to hear that like my theme. :)

To customize the prompt edit the `PROMPT` variable in `alien-minimal.zsh` file and also in `modules/async.zsh`. This should do the job.

You can also use some config variables - for which I have some plans in mind. :)

EDIT:

Updated the theme.
Now it looks like:
<img width="333" alt="screen shot 2017-06-19 at 2 43 17 pm" src="https://user-images.githubusercontent.com/20620104/27276771-0636bfe0-54fe-11e7-86ff-36fc695f6d50.png">
And zshrc:
<img width="304" alt="screen shot 2017-06-19 at 2 46 48 pm" src="https://user-images.githubusercontent.com/20620104/27276810-2f002ec0-54fe-11e7-9de0-f21e4c96c137.png">

**Comment by ijsnow** [comment]
Awesome! Thanks. The variables work like a charm.
