### ISSUE TITLE
RPROMPT expansion and async design

### ISSUE THREAD

**Issue by jbbudzon** [eendroroy/alien-minimal#21]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**

This is more along the lines of a support request or a bug report.

* **What is the current behavior?**

VIM prompt and VERSIONS prompt are not updating properly.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 

I have `AM_ENABLED_VI_PROMPT=1`, `AM_VERSIONS_PROMPT=(PYTHON RUBY NODE)`, `AM_KEEP_PROMPT=1`, and `AM_SEGMENT_UPDATE=0`. Calling `pyenv shell 2.7.15` does not update the python version in the prompt. Hitting `<ESC>` does not properly indicate the vi mode.

* **What is the expected behavior?**

Versions and Vi prompts should update accordingly.

* **What is the motivation / use case for changing the behavior?**

Ensuring that users are kept up to date with the latest information.

* **Please tell us about your environment:**

- Plugin Manager: zplug
- ZSH Version: 5.7.1
- OSX: 10.14

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, etc)

I've actually been meaning to talk with you specifically about the Vi stuff, but in pulling down a recent update it seems the versions prompt is no longer updating either and if we focus on that I may better understand how to submit a PR for the Vi stuff.

So focusing on version prompts, I think what is happening here is that shells are being expanded too early? But at the same time, I don't want to remove the async design...

zsh's `precmd` is executed before every prompt. If I insert a `echo -n $(pyenv version)` here, it always displays the correct and most up to date version.

Inside of `precmd`, we call `am_async_r_prompt`. If I insert an `echo -n $(pyenv version)` here, it always displays the correct and most up to date version.

Inside of `am_r_prompt`, we call `am_r_prompt_complete`. This is the tricky thing... if I insert an `echo -n $(pyenv version)` here, I will always get the version that python was when the shell started. It does not stay up to date. (Almost as if the string is evaluated once at startup and then reused for the remainder of the shell session.)

One easy fix, is to replace the double quotes in `am_r_prompt_complete` to be single quotes. This fixes version prompts for me but also results in RPROMPT calling functions in I believe a very non-async fashion...

So, what is going on here? I would expect that when I debug printed the python version in `am_r_prompt_complete` that it would always be up to date. It does not seem to matter if `AM_KEEP_PROMPT` or `AM_SEGMENT_UPDATE` is set or not.

**Comment by eendroroy** [comment]
Thanks for reporting the issue.

Issue with `pyenv shell 'version'` occurs because of the usage of async job. When a (async) job starts it starts in a new shell and does not pass the `ENV` vars from current shell. As a result `pyenv shell 'version'` does not take effect in async jobs.
Hope fully I will come up with a work around soon.


`AM_SEGMENT_UPDATE` config has been removed a couple of days ago. It no longer has any effect.


`AM_ENABLED_VI_PROMPT` is actually an experimental feature. As I don't use VI mode myself, I haven't given much effort on it yet.

**Comment by jbbudzon** [comment]
Yea, I noticed `AM_SEGMENT_UDPATE` was removed. So glad to see this code is still being worked on! I switched from alien to alien minimal not long ago and have enjoyed every minute of it!! And good to know about the async shell spawning.

My hack for right now fixes the issue for versions but removes async from the RPROMPT. In theory, the vcs portion should work fine in a new shell, just not the versions stuff. I'll play around with my hack more and see if I can get everything else working async.

Lastly, I wanted to say that I believe I have a fix for the VI mode. Once I get this hack worked out so my versions are working properly but I still have async where it's nice to have it, I'll look into submitting a PR. VI mode seems to be broken due to early shell expansion 😛

Edit: Just wanted to point out that tag 1.3.4 works without hack/modification.
Edit2: Looks like 1.4.0 works but 1.4.1 doesn't?

**Comment by eendroroy** [comment]
1.4.0 works because there was a bug in the use of async job. jobs were no actually running asynchronously.

**Comment by eendroroy** [comment]
commit 4efd94f should resolve the issue with `pyenv shell 'version'`

**Comment by jbbudzon** [comment]
Just pulled down this change, but it seems like the `__import_env()` method is having issues.

I put a `set -x`/`set +x` in this method and it seems to be getting weird input:
```
+__import_env:2> read -r line
+__import_env:2> echo $'\C-[[01;31m\C-[[KAM_\C-[[m\C-[[KENABLE_VI_PROMPT=1\n\C-[[01;31m\C-[[KAM_\C-[[m\C-[[KKEEP_PROMPT=1\n\C-[[01;31m\C-[[KAM_\C-[[m\C-[[KSEGMENT_UPDATE=0\n\C-[[01;31m\C-[[KAM_\C-[[m\C-[[KSHOW_FULL_DIR=1\n\C-[[01;31m\C-[[KAM_\C-[[m\C-[[KSHOW_PROCESS_TIME=2\n\C-[[01;31m\C-[[KAM_\C-[[m\C-[[KTHEME=terminal\n\C-[[01;31m\C-[[KAM_\C-[[m\C-[[KUSE_NERD_FONT=1'
+__import_env:3> eval $'export \C-[[01;31m\C-[[KAM_\C-[[m\C-[[KENABLE_VI_PROMPT=1'
(eval):1: bad pattern: ^[[01
...
```

You can see that the `eval export` is choking on `^[[01`. I believe this is due to my grep containing colors by default. Adding a `--color=never` option to the grep command that initializes `__AM_ENVS` fixed the issue for me:
```
+__import_env:2> read -r line
+__import_env:2> echo $'AM_ENABLE_VI_PROMPT=1\nAM_KEEP_PROMPT=1\nAM_SEGMENT_UPDATE=0\nAM_SHOW_FULL_DIR=1\nAM_SHOW_PROCESS_TIME=2\nAM_THEME=terminal\nAM_USE_NERD_FONT=1'
+__import_env:3> eval 'export AM_ENABLE_VI_PROMPT=1'
+(eval):1> export AM_ENABLE_VI_PROMPT=1
...
```

**Comment by jbbudzon** [comment]
With the `__import_env()` issue resolved, I'd expect that I could test the `pyenv shell 2.7.15` output the same way I was before.

I've added an `echo "${PYENV_VERSION}"` to `am_async_r_prompt()` and an `echo -n "test ${PYENV_VERSION} test"` to `am_r_prompt_render()`.
(edit: this echo statement in `am_r_prompt_render()` does indeed come AFTER the `__import_env "${2}"` call)

I then opened a new shell, verified the prompt and debug output was what I expected (ie; `PYENV_VERSION` is not set), and then ran `pyenv shell 2.7.15` (ie; `PYENV_VERSION` is set). Unfortunately, the next prompt and debug output is not what I'd expect:
```

 ~ pyenv shell 2.7.15                                                   test test[PY:2.7.10|RB:2.3.7|⬡ 10.16.3] G:min [4D] 227998f ⭑
2.7.15
 ~                                                                      test test[PY:2.7.10|RB:2.3.7|⬡ 10.16.3] G:min [4D] 227998f ⭑
```

Notice how before the `pyenv` command, `PYENV_VERSION` was not set and therefore we get an empty line followed by a prompt with `test  test`.
Noice how just after the `pyenv` command, `PYENV_VERSION` is set and therefore we get the value of the variable followed by a newline and a prompt. This prompt shows `test  test` instead of `test 2.7.15 test`.

Edit2: FWIW, when I have debug logging in `__import_env` I can see that the PYENV_VERSION is being handled... so not entirely sure what is going on here...
```
+__import_env:2> read -r line
+__import_env:3> eval 'export PYENV_VERSION=2.7.15'
+(eval):1> export PYENV_VERSION=2.7.15
```

**Comment by eendroroy** [comment]
It seems to be working on my mac.

```bash
 am-demo pyenv shell 3.7.2                                  [ 2.7.16| 2.5.0| 9.10.1] 
 am-demo pyenv shell 2.7.15                                  [ 3.7.2| 2.5.0| 9.10.1] 
 am-demo rbenv shell system                                 [ 2.7.15| 2.5.0| 9.10.1] 
 am-demo nodenv shell 5.3.0                                 [ 2.7.15| 2.3.7| 9.10.1] 
 am-demo nodenv shell --unset                                [ 2.7.15| 2.3.7| 5.3.0] 
 am-demo pyenv shell --unset                                [ 2.7.15| 2.3.7| 9.10.1] 
 am-demo rbenv shell --unset                                [ 2.7.16| 2.3.7| 9.10.1] 
 am-demo                                                    [ 2.7.16| 2.5.0| 9.10.1] 
```

Can you share a little bit more about your environment?

Mine is: 
Macbook Pro 2017 (15", core-i7, 16gb Ram) 
Terminal: Iterm2

**Comment by jbbudzon** [comment]
lol now it's working... just pulled down latest again and not having any issues!!

**Comment by eendroroy** [comment]
Glad to hear that :)

If you could share your thought about `VI` stuff I would be happy ......
