### ISSUE TITLE
rprompt do not appear

### ISSUE THREAD

**Issue by gnumoksha** [eendroroy/alien-minimal#22]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] support request

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
right prompt is never show on a specific machine

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 
Use my dotfiles https://gitlab.com/gnumoksha/dotfiles

* **What is the expected behavior?**
alien-minimal show a right prompt

* **What is the motivation / use case for changing the behavior?**
none

* **Please tell us about your environment:**

- Plugin Manager: [antigen | zplug | oh-my-zsh | ... ] `none`
- ZSH Version: `zsh 5.7.1 (x86_64-debian-linux-gnu)`

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, etc)

**Comment by eendroroy** [comment]
Could you please share your `.zshrc` file?

**Comment by eendroroy** [comment]
if you are not using any plugin manager. you can follow below steps:
```bash
cd ~
git clone https://github.com/eendroroy/alien-minimal.git
cd alien-minimal
git submodule update --init --recursive
```
Then set `source ~/alien-minimal/alien-minimal.zsh` in the `~/.zshrc` file.

**Comment by eendroroy** [comment]
> if you are not using any plugin manager. you can follow below steps:
> 
> ```shell
> cd ~
> git clone https://github.com/eendroroy/alien-minimal.git
> cd alien-minimal
> git submodule update --init --recursive
> ```
> 
> Then set `source ~/alien-minimal/alien-minimal.zsh` in the `~/.zshrc` file.

Did you try it? @gnumoksha

**Comment by gnumoksha** [comment]
> > if you are not using any plugin manager. you can follow below steps:
> > ```shell
> > cd ~
> > git clone https://github.com/eendroroy/alien-minimal.git
> > cd alien-minimal
> > git submodule update --init --recursive
> > ```
> > 
> > 
> > Then set `source ~/alien-minimal/alien-minimal.zsh` in the `~/.zshrc` file.
> 
> Did you try it? @gnumoksha

Yes, and it didn't work. I've used a minimal `.zshrc` containing only `source ~/alien-minimal/alien-minimal.zsh` and the rprompt is still empty. Also, all my environment vars are printed on each prompt rendered.

My .zshrc is located here https://gitlab.com/gnumoksha/dotfiles/tree/master/cli/home/config/zsh but alien-minimal does work on one machine with this exact configuration. The problem is with another machine only. How can I debug?

**Comment by eendroroy** [comment]
Which commit are you on?
Could you please try deleting the folder and cloning againg?

**Comment by gnumoksha** [comment]
### Steps
```console
$ git clone https://github.com/eendroroy/alien-minimal.git /tmp/alien-minimal
$ cd /tmp/alien-minimal
$ git log -1
commit fcaf3c67025b5c4e0992a8311d4534a443906b70 (HEAD -> master, tag: 1.4.4, origin/master, origin/HEAD)
Author: indrajit <eendroroy@gmail.com>
Date:   2019-09-03 21:20:39 +0600

    update readme
$ git submodule update --init --recursive
$ echo 'source /tmp/alien-minimal/alien-minimal.zsh' > ~/.zshrc
```

### Results
After close the shell, opening a new one and `cd /tmp/alien-minimal`:
- left prompt is `[S] alien-minimal`
- right prompt is empty
- every new prompt shows all my environment variables (like in https://github.com/eendroroy/alien-minimal/issues/24)

**Comment by sibblegp** [comment]
rprompt also does not appear to me when I am using the current master branch

**Comment by eendroroy** [comment]
What Os you are using?

**Comment by gnumoksha** [comment]
```console
$ lsb_release -a                                                                                                                                                                                                                            
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
$ uname -a                                                                                                                                                                                                                                  
Linux bombadil 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5 (2019-06-19) x86_64 GNU/Linux
$ zsh --version                                                                                                                                                                                                                             
zsh 5.7.1 (x86_64-debian-linux-gnu)
```

**Comment by eendroroy** [comment]
I have made some changes. Please checkout to latest master. Let me know if it resolves the issue.

**Comment by gnumoksha** [comment]
head is now 5f60f560d0ce7bcfc7b471e705163f4e4b53038b and environment variables are no longer show. rprompt is still empty.

**Comment by sibblegp** [comment]
I have updated to master and everything is working great for me.

```No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

Linux radix-gs1 5.0.0-27-generic #28~18.04.1-Ubuntu SMP Thu Aug 22 03:00:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

zsh 5.4.2 (x86_64-ubuntu-linux-gnu)```

**Comment by eendroroy** [comment]
@gnumoksha
> ```
> $ lsb_release -a                                                                                                                                                                                                                            
> No LSB modules are available.
> Distributor ID: Debian
> Description:    Debian GNU/Linux 10 (buster)
> Release:        10
> Codename:       buster
> $ uname -a                                                                                                                                                                                                                                  
> Linux bombadil 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5 (2019-06-19) x86_64 GNU/Linux
> $ zsh --version                                                                                                                                                                                                                             
> zsh 5.7.1 (x86_64-debian-linux-gnu)
> ```

I have tried in a vagrant box. Seems to be working fine.
<img width="977" alt="Screen Shot 2019-09-09 at 8 38 59 PM" src="https://user-images.githubusercontent.com/20620104/64540347-e03deb00-d341-11e9-82ad-67e3cfbf9ed3.png">

With below `.zshrc`
```bash
source /home/vagrant/alien-minimal/alien-minimal.zsh
```

**Comment by gnumoksha** [comment]
@eendroroy I've two machines: home and work. At home, alien-minimal works fine, but at work, it does not show rprompt. I know I've some problem but I can't figure out how to debug it.

**Comment by eendroroy** [comment]
https://github.com/eendroroy/alien-minimal/blob/25fa6df7049a03a5b2d633e9495f36b5251b0b47/alien-minimal.zsh#L51

change the above line to:
```bash
am_r_prompt_render "${PWD}" "${__AM_ENVS}" "${AM_VERSIONS_PROMPT}"
```

then you can use `echo` in any of the files to check if any command is throwing any error.

**Comment by gnumoksha** [comment]
Using `echo am_r_prompt_render "${PWD}" "${__AM_ENVS}" "${AM_VERSIONS_PROMPT}"` results in the following:

![Screenshot from 2019-09-18 13-01-59](https://user-images.githubusercontent.com/696797/65165149-95446780-da14-11e9-93ff-01f3adbbbae9.png)

Any ideas?

**Comment by eendroroy** [comment]
Try using the below:
```bash
echo $(am_r_prompt_render "${PWD}" "${__AM_ENVS}" "${AM_VERSIONS_PROMPT}")
```

**Comment by gnumoksha** [comment]
```zsh
echo \"$(am_r_prompt_render "${PWD}" "${__AM_ENVS}" "${AM_VERSIONS_PROMPT}")\"
```
prints `" "` on non-git directories and `" %F{248}:%f%B%F{78}master%f%b %F{244}[4W]%f %F{248}66fc7eb%f %F{208}%f %F{208}%f "` otherwise

**Comment by eendroroy** [comment]
`RPROMPT` value generation seems perfect. Probably the problem is printing it (or reseting `zle`)

**Comment by gnumoksha** [comment]
Ok. Thank you.
