### ISSUE TITLE
Vi Prompt does not work

### ISSUE THREAD

**Issue by jbbudzon** [eendroroy/alien-minimal#23]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
Report a Bug

* **What is the current behavior?**
Vi indicator does not update as intended.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 
Simply enable Vi mode and toggle between insert mode and normal mode.

* **What is the expected behavior?**
That the indicator update properly.

* **What is the motivation / use case for changing the behavior?**
Expanding our prompt to support vi mode users.

* **Please tell us about your environment:**
- Plugin Manager: zplug
- ZSH Version: 5.7.1

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, etc)
I believe I know why this is happening...

`zle-line-init()` and `zle-keymap-select()` both trigger a method which updates `AM_VI_MODE_IND`. We then trigger a `reset-prompt` which will cause the prompt to "re-render".

I believe the issue with the Vi indicator is that this reset prompt doesn't trigger all of our other methods, rather it just uses the current `RPROMPT` again. For this reason, I believe we need to change `echo -ne "${AM_VI_MODE_IND}"` to `echo -ne '${AM_VI_MODE_IND}`.

This way, your `RPROMPT` variable will be
```
%F{8}[%f%F{2}PY:2.7.10%f%F{8}|%f%F{1}RB:2.3.7%f%F{8}|%f%F{2}⬡ 10.16.3%f%F{8}]%f %F{1}G:%f%B%F{10}min%f%b %F{6}[4D]%f %F{14}227998f%f %F{1}⭑%f ${AM_VI_MODE_IND}
```
instead of
```
%F{8}[%f%F{2}PY:2.7.10%f%F{8}|%f%F{1}RB:2.3.7%f%F{8}|%f%F{2}⬡ 10.16.3%f%F{8}]%f %F{1}G:%f%B%F{10}min%f%b %F{6}[4D]%f %F{14}227998f%f %F{1}⭑%f
```

This, I believe, is what allows the Vi indicator to work properly 😉

**Comment by jbbudzon** [comment]
FWIW, here is my local commit pushed up to my fork. If you'd like I could make a pull request but it's a pretty simple change 😛 

https://github.com/jbbudzon/alien-minimal/commit/0d36abdb1e7c8c7983b33625982e4543f40f9ba1

**Comment by eendroroy** [comment]
Does it properly work with `async` functionality ?

**Comment by eendroroy** [comment]
I have removed `AM_ASYNC_L_PROMPT` option and moved `VI_PROMPT` to left prompt. `VI_PROMPT` should work better now.

https://github.com/eendroroy/alien-minimal/commit/ca7cbd3f8ef05a54f1e47c8ee73634760942f846

**Comment by jbbudzon** [comment]
> Does it properly work with `async` functionality ?

I think this works just fine with the `async` functionality! All we are doing is performing one check against zsh state to determine if we should fill the vi variable with `[I]` or `[N]`. This should be near constant lookup speed.


> I have removed `AM_ASYNC_L_PROMPT` option and moved `VI_PROMPT` to left prompt. `VI_PROMPT` should work better now.
> 
> [ca7cbd3](https://github.com/eendroroy/alien-minimal/commit/ca7cbd3f8ef05a54f1e47c8ee73634760942f846)

Ahhh, if you'd like it moved into left prompt that's ok too! I do happen to like the super minimal left prompt, keeping all "extra data" in the right prompt. But, perhaps I can work on getting a PR together that allows this to be configured easily somehow! 😛


If you'd like to close this out, feel free! I believe the issue will be resolved for anyone using this prompt 😄

**Comment by eendroroy** [comment]
Current solution does not work with `async` workers. I would prefer it working with `async` feature. So let's keep the issue open for now. :)

**Comment by eendroroy** [comment]
How about this?

```bash

export AM_VI_PROMPT_POS=left_start
# (i) am-demo       G:master [1Y,9M] 6fd4c14 @1 + ⭑ ⭑ - - ?

export AM_VI_PROMPT_POS=left_end
# am-demo (i)       G:master [1Y,9M] 6fd4c14 @1 + ⭑ ⭑ - - ?

export AM_VI_PROMPT_POS=right_start
# am-demo       (i) G:master [1Y,9M] 6fd4c14 @1 + ⭑ ⭑ - - ?

export AM_VI_PROMPT_POS=right_end
# am-demo       G:master [1Y,9M] 6fd4c14 @1 + ⭑ ⭑ - - ? (i)
```

**Comment by eendroroy** [comment]
Let me know if you think there is any improvement opportunities.

**Comment by jbbudzon** [comment]
I like it!!

**Comment by jbbudzon** [comment]
Pulled everything down, working great! I can look into investigating doing the vi prompt in a more async fashion, but I'm not entirely certain that (in this very specific case) zsh accounts for this kind of design. The vi prompt is very different than the other things going on in the prompt as it relies entirely on zsh state and not on external tools/output.

**Comment by eendroroy** [comment]
I don't use vi mode on regular basis. So I know very little about how it really works. If you can help me with it, that would be great. :)
