### ISSUE TITLE
Prompt is printing all environment variables

### ISSUE THREAD

**Issue by sibblegp** [eendroroy/alien-minimal#24]
* **I'm submitting a ...**
  - [X ] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
Report a *bug*

* **What is the current behavior?**
When I installed this today on a new system using Antigen, it is outputting all environment variables in the prompt. I see that the theme was updated yesterday. Possibly a bug? I even changed to directly using the git repo and it still has the bug.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 
1) Install Oh My Zsh
2) Install Antigen
3) Include in your .zshrc file: antigen theme https://github.com/eendroroy/alien-minimal.git alien-minimal

My prompt looks like this: https://gist.github.com/sibblegp/dc6f656123e0ce1ef6e7d45b63a0bade

* **What is the expected behavior?**
Not to print all environment variables.

* **What is the motivation / use case for changing the behavior?**
Have it work like it usually does.

* **Please tell us about your environment:**

- Plugin Manager: antigen
- ZSH Version: 5.4.2

**Comment by jbbudzon** [comment]
Hmm, that is odd! I'm not seeing this issue. I'm on tag 1.4.4.

**Comment by eendroroy** [comment]
I don't see it as well.

@sibblegp please try deleting below folder and restarting the shell.

`rm -rf ~/.antigen/bundles/eendroroy/alien-minimal`

**Comment by sibblegp** [comment]
Line 119 in prompt.zsh:

`__import_env "${2}"`

is what is causing all of the environment variables to be printed. When I remove it, they no longer appear.

**Comment by sibblegp** [comment]
Tag 1.4.3 introduced the printing, and I had to go back to 1.4.0 to get no errors. But at least I have a working copy now!

**Comment by gnumoksha** [comment]
I've experienced the same and described here https://github.com/eendroroy/alien-minimal/issues/22#issuecomment-527629055

**Comment by eendroroy** [comment]
I have made some changes. Please checkout to latest master. Let me know if it resolves the issue.

**Comment by sibblegp** [comment]
Although now the left prompt tag is not appearing. I have these settings in my .zshrc file:

```
export AM_PROMPT_END_TAG=' $'
export AM_PROMPT_END_TAG_COLOR=83
```
And there is no $ on my prompt.

**Comment by eendroroy** [comment]
> Although now the left prompt tag is not appearing. I have these settings in my .zshrc file:
> 
> ```
> export AM_PROMPT_END_TAG=' $'
> export AM_PROMPT_END_TAG_COLOR=83
> ```
> 
> And there is no $ on my prompt.

Please try below settings:
```bash
export AM_PROMPT_END_TAG='\ $'
export AM_PROMPT_END_TAG_COLOR=83
```

**Comment by sibblegp** [comment]
Thanks!
