### ISSUE TITLE
wrong node version

### ISSUE THREAD

**Issue by glsorre** [eendroroy/alien-minimal#28]
**Describe the bug**
Using oh my zsh nvm plugin, nvm and alien-minimal.

**To Reproduce**
```shell
 ~ (i) export AM_VERSIONS_PROMPT=(NODE NODE_S)                                


 [⬡ 11.15.0|⬡ 11.15] 
 ~ (i) nvm use 9
Now using node v9.11.2 (npm v5.6.0)

 [⬡ 11.15.0|⬡ 11.15] 
 ~ (i) 

```

**Expected behavior**
I expect the right node version.

**Screenshots**

**Environment:**
- Plugin Manager: [ antibody ]
- ZSH Version: 5.4.2 or 5.3
- Operating System: Ubuntu 18.04 or Mac OS X 
- Terminal Emulator: Tilix 1.7.7 or iTerm 3.0

**Additional context**
When launching ` echo -ne "%F{$AM_NODE_COLOR}${AM_NODE_SYM}$(plib_node_version)%f"` I got the right result

**Comment by eendroroy** [comment]
`nvm` not supported yet. I will try to add it.

**Comment by eendroroy** [comment]
It should work now. Can you please check
<img width="1209" alt="Screenshot 2024-10-27 at 11 18 43 AM" src="https://github.com/user-attachments/assets/e887309b-4acb-4f5d-9cbe-9cbb1ad91b3b">
