### ISSUE TITLE
Not able to replicate the shell

### ISSUE THREAD

**Issue by designMoreWeb** [eendroroy/alien-minimal#29]
**Describe the bug**

So I followed the installation steps and created the ~/.amrc file however the shell is not adapting the theme

**Comment by eendroroy** [comment]
Can I see the content of `.amrc` and a screenshot of your terminal?

**Comment by designMoreWeb** [comment]
gist for .amrc: https://gist.github.com/designMoreWeb/f19f3da7ecca822373a87a63e04f491a
<img width="1236" alt="Screenshot 2019-10-16 at 1 39 42 PM" src="https://user-images.githubusercontent.com/5986856/66944109-8e604300-f01a-11e9-93a2-7f58b1be0bc1.png">

**Comment by eendroroy** [comment]
Try using the below `~/.amrc`:

```zsh
#!/usr/bin/env zsh

export AM_THEME=soft
export AM_USE_NERD_FONT=1
export AM_KEEP_PROMPT=1
export AM_ASYNC_L_PROMPT=1
```

Please provide me the below information and the installation procedure as well:

- Plugin Manager: [ antigen | zplug | ... ]
- ZSH Version:
- Operating System: [ name and version ]
- Terminal Emulator: [ name and version ]

**Comment by designMoreWeb** [comment]
Plugin Manager: [ antigen ]
ZSH Version: [zsh 5.7.1 (x86_64-apple-darwin18.2.0)]
Operating System: [ Mac Mojave Version 10.14.6 ]
Terminal Emulator: [Hyper 3.0.2 (stable)]

I tried adding the settings for _~/.amrc_
however no change

**Comment by designMoreWeb** [comment]
Any progress on this issue?

**Comment by eendroroy** [comment]
I am trying to reproduce it. It happened only the first time I opened the `hyper` after installation.
Afterwards the shell is rendering as expected every time.

<img width="650" alt="Screen Shot 2019-10-30 at 9 21 54 PM" src="https://user-images.githubusercontent.com/20620104/67872060-97452e80-fb5b-11e9-9388-64e7bbc18e0a.png">
