### ISSUE TITLE
Async background update of prompt

### ISSUE THREAD

**Issue by pszypowicz** [eendroroy/alien-minimal#33]
**Is your feature request related to a problem? Please describe.**
If I have 2 terminal windows opened and in the same git folder, If I switch to different branch in one, the other one does not auto update in the background, still showing the previous branch.

**Describe the solution you'd like**
It would be good if the prompt could be updated in background, so if I have 2 windows with terminal in the same git repo, and I change branch in one, the other would refresh itself showing new branch. This would also be useful when you switch branch in some other software, like vscode.

**Comment by eendroroy** [comment]
The use of the background job is to minimize the time to make the prompt usable.

**Comment by eendroroy** [comment]
The use of the background job is to minimize the time to make the prompt usable.
The feature you are proposing would require a job that will keep running in the background. Which is not the intention of the theme.

It can be done by a separate tool that will keep track of the terminal windows and update the prompt whenever required.
