### ISSUE TITLE
Directory in prompt disappears

### ISSUE THREAD

**Issue by ijsnow** [eendroroy/alien-minimal#4]
Hey, friend. Still loving the theme. I was wondering if you had this issue that I'm having. It may have came about with the variables from my last issue. 

The directory portion of my prompt will disappear after x amount of time and will reappear next time I enter a command. I never notice if it is caused by something weird happening with my terminal or if it just randomly switches. I'll attach a screenshot for example.

![image](https://user-images.githubusercontent.com/11557758/29426852-c8e2b9e2-833c-11e7-9082-57c02af889c7.png)

Here's the info that get's loaded from my `.zshrc` file

```
PROMPT_START_TAG='→ '
PROMPT_END_TAG=' $'
PROMPT_START_TAG_COLOR=71
PROMPT_END_TAG_COLOR=71

source ~/.oh-my-zsh/antigen.zsh

antigen use oh-my-zsh

...antigen bundle random stuff

antigen bundle https://github.com/eendroroy/alien-minimal.git

antigen apply
```

It's not a big deal. It's been happening for a while and hasn't disrupted me, just figured I'd post this to see if you had a simple solution! Thanks!

**Comment by eendroroy** [comment]
I am on mac. There is a bug that makes all the colors black and white. But that's different than your issue. Let me check on a ubuntu machine.

The color issue occurs in ubuntu too. The whole prompt goes black when the emulator is minimized or maximized. But not only the directory promot.

![002](https://user-images.githubusercontent.com/20620104/29444740-db6a6b92-8403-11e7-8e8f-a21986889e36.png)

**Comment by ijsnow** [comment]
I'm actually on a Mac too. Using iTerm. And no rush by the way! Don't want you to waste time on this if you have more important things to do :) it's pretty low priority.

**Comment by eendroroy** [comment]
I also have the exact same issue.

This is also my default terminal theme. So I also need the fix :)

**Comment by eendroroy** [comment]
Hi @ijsnow, could you please check if the issue still exists after update?

**Comment by ijsnow** [comment]
From first look, it seems to be fixed! I'll let you know if I ever see it again. Thanks! Nice work on the fix 👍

**Comment by eendroroy** [comment]
Thanks. :)
