### ISSUE TITLE
option to change color of PROMPT_START_TAG depending on exit code

### ISSUE THREAD

**Issue by jkhsjdhjs** [eendroroy/alien-minimal#5]
As the title says, an option to color the start tag red if the exit code is not null and blue else, leaving the current directory color unchanged, would be nice.

Also I'd like to have an option to show the full path instead of only the directory between start and end tag.

**Comment by eendroroy** [comment]
Thanks for the suggestion.
Hope to do it soon.

**Comment by eendroroy** [comment]
Probably this the configuration you are looking for. Let me know if I got it correct.

    export AM_UPDATE_L_PROMPT=0
    export AM_SHOW_FULL_DIR=1

    export PROMPT_START_TAG='>> '
    export PROMPT_END_TAG=' $$'
    export PROMPT_START_TAG_COLOR=81
    export PROMPT_END_TAG_COLOR=81

    export AM_ERROR_ON_START_TAG=1

**Comment by jkhsjdhjs** [comment]
Yes! Also it would be nice if you could add an option to customize the error color.
But thank you very much so far!

I have just one little issue currently:
When I try to use the percent sign as prompt end tag (`export PROMPT_END_TAG=' %'`) I get the following:
`>> ~ %f` (https://screens.totally.rip/2017/11/5a078eb8e6212.png)

**Comment by eendroroy** [comment]
Added option to customize color scheme. [color-themes](https://github.com/eendroroy/alien-minimal/blob/master/README.md#color-themes)

Regarding the end_tag - the '%' sign is an escape character in zsh. use '%%' like this:
    
    export PROMPT_END_TAG=' %%'

this should solve your issue.

**Comment by jkhsjdhjs** [comment]
Thanks you very much! Works perfectly!
