### ISSUE TITLE
setting AM_ERROR_ON_START_TAG=0 uses short path on exit code = 0

### ISSUE THREAD

**Issue by jkhsjdhjs** [eendroroy/alien-minimal#6]
When you set AM_ERROR_ON_START=0 the prompt shows the short path to the current directory when the exit code of the program previously ran is 0.

```
 >> ~/dotfiles % export AM_ERROR_ON_START_TAG=0
 >> dotfiles % false
 >> ~/dotfiles % 1 true
 >> dotfiles %
```

**Comment by eendroroy** [comment]
Fixed a typo. Please check now.
