### ISSUE TITLE
AM_UPDATE_L_PROMPT is not working anymore or delay too short

### ISSUE THREAD

**Issue by jkhsjdhjs** [eendroroy/alien-minimal#7]
The title says it. The change to the short directory is noticable on my Odroid C2, but on my desktop it seems like it only prints the short directory.

**Comment by eendroroy** [comment]
What are the configuration variables you are using?

**Comment by jkhsjdhjs** [comment]
```
export PROMPT_START_TAG='>> '
export PROMPT_END_TAG=' %%'
export PROMPT_START_TAG_COLOR=10
export PROMPT_END_TAG_COLOR=81
export AM_SHOW_FULL_DIR=1
export AM_ERROR_ON_START_TAG=1
export am_error_color=9
```

As I noticed this error I had AM_UPDATE_L_PROMPT=1 exported manually.

**Comment by eendroroy** [comment]
I guess your desktop is really fast :)
All my devices are changing the prompt with a noticeable delay.
I will try setting a delay manually.

**Comment by jkhsjdhjs** [comment]
Hmm, in the beginning I also had a noticeable delay of around 0.5s - 1s, but now it shows the short path instantly.

I really don't think it's because of the speed of my desktop. On my Odroid C2 (ARM, 4x 1,5GHz) - it really don't has that much power - it's also hardly noticeable. The full path is printed there for around 0.2s or less.

**Comment by eendroroy** [comment]
Could you check setting a delay in `modules/prompt.zsh` after line `45`, something like this:

```bash
   44   if [[ $AM_UPDATE_L_PROMPT == 1 ]];then
   45     PROMPT='`am_ssh_st`$__time`am_venv` `am_prompt_general_short_dir` '
+  46     sleep .1
   47     zle && zle reset-prompt
   48   fi
```

**Comment by jkhsjdhjs** [comment]
I added `sleep 1` and the change still isn't noticeable on my desktop.

EDIT: I'm stupid, sry. Didn't open a new session. The change now occurs one second after issuing the command.

**Comment by eendroroy** [comment]
1 second delay is actually too long. Not sure why it's happening.
I will review the whole code and let you know.

**Comment by eendroroy** [comment]
Hi,

Sorry for delaying this much. I have to admit, I am clueless about this issue. Do you have any thought about it?

**Comment by jkhsjdhjs** [comment]
Hm, not yet, but I didn't take a deep look into the code yet.
But were you able to reproduce it or not?

**Comment by eendroroy** [comment]
I wasn't able to reproduce it. Not sure if I am missing something.
I tried with the following config:

```
export PROMPT_START_TAG='> '
export PROMPT_END_TAG=' -'
export AM_SHOW_FULL_DIR=1
export AM_ERROR_ON_START_TAG=1
export AM_UPDATE_L_PROMPT=1
```

**Comment by jkhsjdhjs** [comment]
I also hide the exit code in my config, but the problems persits when I disable that.
All other settings I have are just color settings and a different start and end tag, but that shouldn't be the problem.

EDIT: I tried it with the same settings you use, but I'm still experiencing this problem.
EDIT2: I'm using your theme with oh-my-zsh btw, maybe that is causing the proiblem. But it would be weird if so cause I've been using this theme only with oh-my-zsh yet and it did work in the beginning.

**Comment by eendroroy** [comment]
I will check again with oh-my-zsh then. Thanks for the heads up, it didn't come to me. :)

**Comment by eendroroy** [comment]
Could you try moving all configs (alien-minimal configs) before setting the theme?
Something like this: [zshrc](https://raw.githubusercontent.com/eendroroy/dotfiles/master/common/zshrc.symlink)

**Comment by jkhsjdhjs** [comment]
I don't exactly understand what you mean by moving all configs before setting the theme.
Do you mean that I should try to export all settings before setting ZSH_THEME in my .zshrc?

**Comment by eendroroy** [comment]
Yes, that is what I meant. I have noticed some configurations do not work if configured after setting `ZSH_THEME` in `.zshrc`.

**Comment by jkhsjdhjs** [comment]
Ok, tried that, but it doesn't change anything :/

**Comment by eendroroy** [comment]
:(

**Comment by eendroroy** [comment]
I was able to reproduce it on a freshly installed mac os.
It has actually nothing to do with the configurations and only happening because of the CPU is working fast.
I guess right now there is no quick solution to it. :(
